subin/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # 예시 : blog/
    path('', views.PostLV.as_view(), name='index'),
    
    # 예시: blog/post
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    # 예시 : blog/post/슬러그-슬러그-슬러그
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    # 예시 : blog/archive
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # 예시 : blog/archive/2022 
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    
    # 예시 : blog/archive/2022/9월
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    
    # 예시 : blog/archive/2022/9월/16
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    
    # 예시 : blog/archive/today
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/', views.SearchFV.as_view(), name='search'),
    
    path('add/', views.PostCreateView.as_view(), name='add'),
    
    path('change/', views.PostChangeLV.as_view(), name='change'),
    
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

subin/board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:board_id>/create_reply', views.create_reply, name='create_reply'),
]

subin/codi/urls.py
from django.urls import path
from codi import views

app_name='codi'
urlpatterns = [
    path('', views.CategoryLV.as_view(), name='index'),
    path('category', views.CategoryLV.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDV.as_view(), name='category_detail'),
    path('codi/<int:pk>/', views.CodiDV.as_view(), name='codi_detail'),

    path('category/add/', views.CategoryCV.as_view(),name='category_add'),
    path('category/change/', views.CategoryChangeLV.as_view(), name='category_change'),
    path('category/<int:pk>/update/', views.CategoryUV.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelV.as_view(), name='category_delete'),
    
    path('codi/add/', views.CodiCV.as_view(),name='codi_add'),
    path('codi/change/', views.CodiChangeLV.as_view(), name='codi_change'),
    path('codi/<int:pk>/update/', views.CodiUV.as_view(), name='codi_update'),
    path('codi/<int:pk>/delete/', views.CodiDelV.as_view(), name='codi_delete'),
]

subin/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('codi/', include('codi.urls')),
    path('board/', include('board.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subin/templates/base.html
<!DOCTYPE html>
<html lang="ko">

    {% load static%}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- 제목 블록 Start (기본값 My Blog Page) -->
    <title>    
        {% block title %}
        My Blog Page
        {% endblock %}
    </title>
    <!-- 제목 블록 End -->

    <!-- Bootstrap CSS only -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- font change [pretendard] -->
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo&display=swap" rel="stylesheet">
    <!-- 공통 스타일 적용 Start -->
    <style>
        * {
            font-family: 'Heebo', sans-serif;
        }
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        #main-wrapper{
            margin: 60px 0;
            height: auto;
            min-height: 100%;
            padding-bottom: 266px;
        }
        footer {
            height: 266px;
            position: relative;
            transform : translateY(-100%);
            width: 100%;
            padding: 60px 0;
            background: #252629;
        }
        #contact_info  * {
            color: #96989c;
            font-size: 14px;
        }
    
        footer .footer_logo {
            padding-bottom: 24px;
            color: #fff;
            font-weight: 600;
            
        }
    </style>
    <!-- 공통 스타일 적용 End -->

    <!-- 스타일 블록 Start -->
    {% block extra-style %}

    {% endblock %}
    <!-- 스타일 블록 End -->
</head>

<body>
    <!-- 네비게이션 바 Start -->
    <nav class="navbar navbar-expand-lg navbar-3 dark bg-dark">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic"><a class='nav-link text-white' href="{% url 'home' %}">&nbsp;&nbsp;<img src="{% static 'img/shop (5).png' %}" width="38px">&nbsp; Fashion Blog</a></span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">Post</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'codi:index' %}">Codi</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'board:index' %}">Board</a>
                </li>
                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'codi:category_add' %}">Category</a>
                        <a class="dropdown-item" href="{% url 'codi:codi_add' %}">Codi</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'codi:category_change' %}">Category</a>
                        <a class="dropdown-item" href="{% url 'codi:codi_change' %}">Codi</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                        <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                    </div>
                </li>
            </ul>
            <!-- 
            <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
            
            <!--  -->
            <ul class="navbar-nav mx-5">
                <li class="nav-item dropdown mx-1 btn btn-dark">
                    {% if user.is_active %} <!-- 로그인된 상태라면 -->
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                    {% else %} <!-- 로그인된 상태가 아니라면 -->
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        로그인 / 회원가입
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                    {% endif %}
                </li>
            </ul>
            <!--  -->
        </div>
    </nav>
    <!-- 네비게이션 바 End -->

    <div id="main-wrapper">
        <div id="main-content" class="container">
            <!-- 콘텐츠 블록 Start -->
            {% block content %}
            {% endblock %}
            <!-- 콘텐츠 블록 End -->
        </div>
    </div>

    <!-- 푸터 Start -->
    <footer>
        <div class="container">
            <div class="footer_logo">My Blog</div>
            <div id="contact_info">
                <p>
                    <a class="text-decoration-none" href="tel:+821090133764"><i class="fa-solid fa-phone"></i>&emsp;010-9013-3764</a>
                    <br>
                    <a class="text-decoration-none" href="mailto:bigdata0607@gmail.com"><i class="fa-solid fa-envelope"></i>&emsp;bigdata0607@gmail.com</a>
                    <br>
                    <a class="text-decoration-none" href="https://subindata.tistory.com/" target="_blank"><i class="fa fa-globe"></i>&emsp;subin00</a>
                </p>
            </div>
            <p style="color:#646873">Copyright © <b>Nam Su Bin</b> All rights reserved.</p>
        </div>
    </footer>
    <!-- 푸터 End -->
</body>

<script src="https://kit.fontawesome.com/600ceba5b1.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->
</html>

subin/templates/home.html
{% extends 'base.html'%}

{% load static%}

{% block title %}
Home
{% endblock %}

{% block extra-style%}
<link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="'title">Welcome to my blog <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-emoji-laughing" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M12.331 9.5a1 1 0 0 1 0 1A4.998 4.998 0 0 1 8 13a4.998 4.998 0 0 1-4.33-2.5A1 1 0 0 1 4.535 9h6.93a1 1 0 0 1 .866.5zM7 6.5c0 .828-.448 0-1 0s-1 .828-1 0S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 0-1 0s-1 .828-1 0S9.448 5 10 5s1 .672 1 1.5z"/>
          </svg></h2>
    </div>
   
    <hr style="margin:10px 0;">

    <div class="row text-center">
        <div class="col">
            <h4>👗About the blog👜</h4>
            <p>My blog is a fashion (Kolon Mall) blog. The blog provides various articles related to fashion.<br>
                We also show popular products at Kolon Mall. You can also add content that is not on the blog directly.<br>
                You are also free to write comments about your blog.<br>
                I hope you receive a lot of information about fashion from your blog. Thank you for visiting.
                
            </p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="'fixed-bottom bg-info">
    <h4>This is FOOTER area</h4>
</footer>
{% endblock %}